---
# Source: aws-ebs-csi-driver/templates/clusterrole-node.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebs-csi-node
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames:
      - ebs-csi-node
