language: go
go_import_path: github.com/bertinatto/ebs-csi-driver

go:
  - "1.10.x"
  - "1.11.x"
  - master

before_install:
  - go get github.com/mattn/goveralls

script:
  - make
  - make test
  - make test-sanity
  - go test -covermode=count -coverprofile=profile.cov ./pkg/...
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

