kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv2
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc2
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0904658a78a1abe84
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - eu-north-1a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc2
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-linux-volume2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.ebs.csi.aws.com/zone
                operator: In
                values:
                  - eu-north-1a
  containers:
    - image: ubuntu:latest
      # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      name: test-container
      volumeMounts:
        - mountPath: /test-ebs
          name: persistent-storage
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: ebs-claim2
