kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-windows
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  claimRef:
    namespace: default
    name: ebs-claim-windows
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0030720fd47491048
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - us-east-2c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim-windows
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-windows-volume
spec:
  containers:
  - image: ubuntu:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: test-pv-windows
  volumes:
  - name: test-pv-windows
    persistentVolumeClaim:
      claimName: ebs-claim-windows
