version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
executors:
  golang:
    docker:
      - image: beyondsecurity/golang
jobs:
  build-docker:
    working_directory: ~/project
    executor: golang
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: Build Docker image
          command: docker build . -t $ACR_NAME.azurecr.io/ebs-csi-driver:${CIRCLE_SHA1:0:7}
      - when:
          condition:
            or:
              - and:
                - equal: [master, << pipeline.git.branch >>]
          steps:
            - run:
                name: Push to ACR
                command: |
                  LOGIN_COMMAND=$(docker login wizio.azurecr.io --username $ACR_SP_ID --password $ACR_SP_PWD)
                  $LOGIN_COMMAND
                  docker push $ACR_NAME.azurecr.io/ebs-csi-driver:${CIRCLE_SHA1:0:7}

workflows:
  version: 2
  build:
    jobs:
      - build-docker:
          context: BuildContext
