controller:
  extraArgs:
    enable-ssl-passthrough: true
  nodeSelector: 
    node-role.kubernetes.io/node: "atcis"
  kind: DaemonSet
  daemonset:
    useHostPort: true
  tolerations:
    - key: tenant
      value: atcis
      effect: NoSchedule
  scope:
    namespace: atcis