apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ebs-csi-controller
  labels:
    {{ include "aws-ebs-csi-driver.labels" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{ include "aws-ebs-csi-driver.selectorLabels" . }}
