{{- if .Values.enableVolumeSnapshot }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snapshot-controller-leaderelection
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: ebs-snapshot-controller
roleRef:
  kind: Role
  name: snapshot-controller-leaderelection
  apiGroup: rbac.authorization.k8s.io

{{- end }}
