{{- if .Values.enableVolumeSnapshot }}
#Snapshot controller
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ebs-snapshot-controller
  namespace: kube-system
spec:
  serviceName: ebs-snapshot-controller
  replicas: 1
  selector:
    matchLabels:
      app: ebs-snapshot-controller
  template:
    metadata:
      labels:
        app: ebs-snapshot-controller
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        {{- with .Values.nodeSelector }}
{{ toYaml . | indent 8 }}
        {{- end }}
      tolerations:
        - operator: Exists
      {{- with .Values.tolerations }}
{{ toYaml . | indent 8 }}
      {{- end }}
      serviceAccount: ebs-snapshot-controller
      containers:
        - name: snapshot-controller
          image: quay.io/k8scsi/snapshot-controller:v2.0.1
          args:
            - --v=5
            - --leader-election=false
{{- end }}
